# pdf_generator.py
# Generates professional ESG reports as downloadable PDFs
# Fixed the multi_cell crash from prototype 1 - width is now 180 not 0

from fpdf import FPDF
from datetime import datetime

# A4 page is 210mm wide, with 15mm margins each side = 180mm content width
# never use 0 as the width in multi_cell - that was the bug in prototype 1
CONTENT_WIDTH = 180
MARGIN = 15


class VeridexPDF(FPDF):

    def header(self):
        self.set_fill_color(3, 11, 24)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(0, 212, 170)
        self.set_xy(MARGIN, 4)
        self.cell(0, 6, "VERIDEX", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 7)
        self.set_text_color(100, 116, 139)
        self.set_x(MARGIN)
        self.cell(0, 5, "ESG Intelligence Platform  |  Confidential")
        self.set_y(22)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(100, 116, 139)
        self.cell(
            0, 8,
            f"Page {self.page_no()}  |  Generated by Veridex  |  {datetime.now().strftime('%d %B %Y')}",
            align="C"
        )

    def section_title(self, title):
        self.ln(5)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(0, 212, 170)
        self.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(0, 212, 170)
        self.set_line_width(0.4)
        self.line(MARGIN, self.get_y(), MARGIN + CONTENT_WIDTH, self.get_y())
        self.ln(3)
        self.set_text_color(30, 41, 59)

    def score_box(self, label, value, sub, x, y, w=43, h=22):
        self.set_fill_color(9, 21, 40)
        self.set_draw_color(15, 32, 64)
        self.rect(x, y, w, h, "FD")
        self.set_xy(x + 2, y + 2)
        self.set_font("Helvetica", "", 6)
        self.set_text_color(100, 116, 139)
        self.cell(w - 4, 4, label.upper(), align="C")
        self.set_xy(x + 2, y + 7)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(0, 212, 170)
        self.cell(w - 4, 6, str(value), align="C")
        self.set_xy(x + 2, y + 14)
        self.set_font("Helvetica", "", 6)
        self.set_text_color(100, 116, 139)
        self.cell(w - 4, 4, str(sub), align="C")


def generate_report(df, company_name):
    """
    Builds a full multi page ESG report for the selected company.
    Returns the PDF as bytes so Streamlit can offer a download button.
    """
    from esg_scorer import get_fallback_recommendations

    pdf = VeridexPDF()
    pdf.set_margins(MARGIN, 25, MARGIN)
    pdf.set_auto_page_break(auto=True, margin=18)

    company_df = df[df["Company"] == company_name].sort_values("Year")
    if company_df.empty:
        pdf.add_page()
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 10, f"No data found for {company_name}")
        return bytes(pdf.output())

    latest   = company_df.iloc[-1].to_dict()
    sector   = latest.get("Sector", "N/A")
    year     = int(latest.get("Year", 2024))
    esg      = round(float(latest.get("Overall_ESG_Score", 0)), 1)
    env      = round(float(latest.get("Environmental_Score", 0)), 1)
    soc      = round(float(latest.get("Social_Score", 0)), 1)
    gov      = round(float(latest.get("Governance_Score", 0)), 1)

    if esg >= 80:   rating = "Excellent"
    elif esg >= 65: rating = "Good"
    elif esg >= 50: rating = "Fair"
    else:           rating = "Poor"

    # ── PAGE 1: COVER ──────────────────────────────────────
    pdf.add_page()

    pdf.set_fill_color(3, 11, 24)
    pdf.rect(0, 20, 210, 55, "F")
    pdf.set_xy(MARGIN, 28)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(0, 212, 170)
    pdf.cell(0, 10, "ESG PERFORMANCE REPORT", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(MARGIN)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(226, 232, 240)
    pdf.cell(0, 9, company_name.upper(), new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(MARGIN)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 6, f"{sector} Sector  |  Year {year}  |  {datetime.now().strftime('%d %B %Y')}")

    pdf.set_y(85)
    pdf.set_font("Helvetica", "B", 44)
    pdf.set_text_color(0, 212, 170)
    pdf.cell(0, 18, str(esg), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 7, f"Overall ESG Score  |  {rating}", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(8)
    bw = 44
    bx = MARGIN
    by = pdf.get_y()
    pdf.score_box("Environmental", env, "E Score", bx,        by, bw)
    pdf.score_box("Social",        soc, "S Score", bx+bw+3,   by, bw)
    pdf.score_box("Governance",    gov, "G Score", bx+bw*2+6, by, bw)
    pdf.set_y(by + 30)

    # ── PAGE 2: METRICS ────────────────────────────────────
    pdf.add_page()
    pdf.section_title("ESG Score Summary")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(71, 85, 105)
    summary = (
        f"{company_name} recorded an overall ESG score of {esg} for {year}, "
        f"rated '{rating}'. Environmental scored {env}, Social {soc}, "
        f"and Governance {gov}. This report covers key metrics and improvement areas."
    )
    pdf.multi_cell(CONTENT_WIDTH, 6, summary)
    pdf.ln(3)

    pdf.section_title("Key ESG Metrics")
    metrics = [
        ("Renewable Energy",        f"{latest.get('Renewable_Energy_Percentage','N/A')}%"),
        ("Total Emissions",         f"{latest.get('Total_Emissions','N/A')} Mt CO2e"),
        ("Gender Diversity",        f"{latest.get('Gender_Diversity_Percentage','N/A')}%"),
        ("Board Diversity",         f"{latest.get('Board_Diversity_Percentage','N/A')}%"),
        ("Employee Turnover",       f"{latest.get('Employee_Turnover_Percentage','N/A')}%"),
        ("Training Hours/Employee", f"{latest.get('Training_Hours_Per_Employee','N/A')} hrs"),
        ("Workplace Injury Rate",   f"{latest.get('Workplace_Injury_Rate','N/A')}"),
        ("Independent Board",       f"{latest.get('Independent_Board_Percentage','N/A')}%"),
        ("ESG Linked Pay",          str(latest.get('ESG_Linked_Compensation_Yes_No','N/A'))),
        ("Carbon Target",           f"{latest.get('Carbon_Reduction_Target_Percentage','N/A')}%"),
        ("Sustainability Invest",   f"${latest.get('Sustainability_Investment','N/A')}B"),
        ("Revenue",                 f"${latest.get('Revenue','N/A')}B"),
    ]

    cw = (CONTENT_WIDTH - 4) / 2
    row_y = pdf.get_y()
    for i, (label, value) in enumerate(metrics):
        col = i % 2
        if col == 0 and i > 0:
            row_y = pdf.get_y()
        x = MARGIN + col * (cw + 4)
        fill = (248, 250, 252) if (i // 2) % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*fill)
        pdf.set_xy(x, row_y)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(cw * 0.6, 7, label, border=1, fill=True)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(cw * 0.4, 7, str(value), border=1, fill=True,
                 new_x="LMARGIN" if col == 1 else "RIGHT",
                 new_y="NEXT" if col == 1 else "TOP")

    pdf.ln(6)

    # ── PAGE 3: RECOMMENDATIONS ────────────────────────────
    pdf.add_page()
    pdf.section_title("Improvement Recommendations")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(71, 85, 105)
    pdf.multi_cell(CONTENT_WIDTH, 6,
        "The following recommendations are based on this company's actual ESG metrics "
        "compared against sector benchmarks and best practice thresholds."
    )
    pdf.ln(4)

    recs = get_fallback_recommendations(company_name, latest, sector, None)
    for i, tip in enumerate(recs, 1):
        tip_str = str(tip)
        y_before = pdf.get_y()
        pdf.set_fill_color(0, 212, 170)
        pdf.rect(MARGIN, y_before + 1, 6, 6, "F")
        pdf.set_xy(MARGIN + 0.5, y_before + 1.5)
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(3, 11, 24)
        pdf.cell(5, 5, str(i))
        pdf.set_xy(MARGIN + 10, y_before)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 41, 59)
        # using CONTENT_WIDTH - 10 leaves room for the number box
        pdf.multi_cell(CONTENT_WIDTH - 10, 6, tip_str)
        pdf.ln(2)

    # methodology note
    pdf.ln(4)
    pdf.section_title("Methodology")
    pdf.set_fill_color(9, 21, 40)
    pdf.rect(MARGIN, pdf.get_y(), CONTENT_WIDTH, 28, "F")
    pdf.set_xy(MARGIN + 4, pdf.get_y() + 3)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(0, 212, 170)
    pdf.cell(0, 5, "About Veridex Scoring", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(MARGIN + 4)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(148, 163, 184)
    note = (
        "Veridex scores are calculated from 16 raw operational metrics across E, S and G pillars. "
        "Weights are fully transparent and adjustable -- unlike commercial providers who use hidden methodologies. "
        "The predictive model uses Random Forest Regression (R2=0.833). "
        "This report is for informational purposes only and does not constitute financial advice."
    )
    pdf.multi_cell(CONTENT_WIDTH - 8, 5, note)

    return bytes(pdf.output())